### ISSUE TITLE
org.json.JSONException: JSONObject["lastFailedBuild"] is not a JSONObject.

### ISSUE THREAD

**Issue by toby1984** [Voipfuture-GmbH/tphs100-client#3]
Application crashes when Jenkins returns a NULL value for the "lastFailedBuild" property (which arguably is no object).

```
Exception in thread "main" org.json.JSONException: JSONObject["lastFailedBuild"] is not a JSONObject.
        at org.json.JSONObject.getJSONObject(JSONObject.java:641)
        at de.codesourcery.tplink.JenkinsClient.wasFailedJob(JenkinsClient.java:242)
        at de.codesourcery.tplink.JenkinsClient.getJobs(JenkinsClient.java:217)
        at de.codesourcery.tplink.Main.main(Main.java:159)
```

**Comment by toby1984** [comment]
fixed in commit bf95ab28d653c17342e0aff473a97760ec32688e
